//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 18/07/2012 07:55:54
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace AdventureWorks.Domain
{

    /// <summary>
    /// Street address information for customers.
    /// </summary>
    public partial class Address {

        private int _AddressID;

        private string _AddressLine1;

        private string _AddressLine2;

        private string _City;

        private string _StateProvince;

        private string _CountryRegion;

        private string _PostalCode;

        private System.Guid _Rowguid;

        private System.DateTime _ModifiedDate;

        private Iesi.Collections.ISet _CustomerAddresses;

        private Iesi.Collections.ISet _SalesOrderHeaders_ShipToAddressID;

        private Iesi.Collections.ISet _SalesOrderHeaders_BillToAddressID;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Address()
        {
            this._CustomerAddresses = new Iesi.Collections.HashedSet();
            this._SalesOrderHeaders_ShipToAddressID = new Iesi.Collections.HashedSet();
            this._SalesOrderHeaders_BillToAddressID = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// Primary key for Address records.
        /// </summary>
        public virtual int AddressID
        {
            get
            {
                return this._AddressID;
            }
            set
            {
                this._AddressID = value;
            }
        }

    
        /// <summary>
        /// First street address line.
        /// </summary>
        public virtual string AddressLine1
        {
            get
            {
                return this._AddressLine1;
            }
            set
            {
                this._AddressLine1 = value;
            }
        }

    
        /// <summary>
        /// Second street address line.
        /// </summary>
        public virtual string AddressLine2
        {
            get
            {
                return this._AddressLine2;
            }
            set
            {
                this._AddressLine2 = value;
            }
        }

    
        /// <summary>
        /// Name of the city.
        /// </summary>
        public virtual string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this._City = value;
            }
        }

    
        /// <summary>
        /// Name of state or province.
        /// </summary>
        public virtual string StateProvince
        {
            get
            {
                return this._StateProvince;
            }
            set
            {
                this._StateProvince = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CountryRegion in the schema.
        /// </summary>
        public virtual string CountryRegion
        {
            get
            {
                return this._CountryRegion;
            }
            set
            {
                this._CountryRegion = value;
            }
        }

    
        /// <summary>
        /// Postal code for the street address.
        /// </summary>
        public virtual string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this._PostalCode = value;
            }
        }

    
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public virtual System.Guid Rowguid
        {
            get
            {
                return this._Rowguid;
            }
            set
            {
                this._Rowguid = value;
            }
        }

    
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        public virtual System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this._ModifiedDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CustomerAddresses in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet CustomerAddresses
        {
            get
            {
                return this._CustomerAddresses;
            }
            set
            {
                this._CustomerAddresses = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SalesOrderHeaders_ShipToAddressID in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet SalesOrderHeaders_ShipToAddressID
        {
            get
            {
                return this._SalesOrderHeaders_ShipToAddressID;
            }
            set
            {
                this._SalesOrderHeaders_ShipToAddressID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SalesOrderHeaders_BillToAddressID in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet SalesOrderHeaders_BillToAddressID
        {
            get
            {
                return this._SalesOrderHeaders_BillToAddressID;
            }
            set
            {
                this._SalesOrderHeaders_BillToAddressID = value;
            }
        }
    }

}
