//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 18/07/2012 07:55:54
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace Northwind.Domain
{

    /// <summary>
    /// Products sold or used in the manfacturing of sold products.
    /// </summary>
    public partial class Product {

        private int _ProductID;

        private string _Name;

        private string _ProductNumber;

        private string _Color;

        private decimal _StandardCost;

        private decimal _ListPrice;

        private string _Size;

        private System.Nullable<decimal> _Weight;

        private System.DateTime _SellStartDate;

        private System.Nullable<System.DateTime> _SellEndDate;

        private System.Nullable<System.DateTime> _DiscontinuedDate;

        private byte[] _ThumbNailPhoto;

        private string _ThumbnailPhotoFileName;

        private System.Guid _Rowguid;

        private System.DateTime _ModifiedDate;

        private ProductModel _ProductModel;

        private ProductCategory _ProductCategory;

        private Iesi.Collections.ISet _SalesOrderDetails;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Product()
        {
            this._SalesOrderDetails = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// Primary key for Product records.
        /// </summary>
        public virtual int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this._ProductID = value;
            }
        }

    
        /// <summary>
        /// Name of the product.
        /// </summary>
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }

    
        /// <summary>
        /// Unique product identification number.
        /// </summary>
        public virtual string ProductNumber
        {
            get
            {
                return this._ProductNumber;
            }
            set
            {
                this._ProductNumber = value;
            }
        }

    
        /// <summary>
        /// Product color.
        /// </summary>
        public virtual string Color
        {
            get
            {
                return this._Color;
            }
            set
            {
                this._Color = value;
            }
        }

    
        /// <summary>
        /// Standard cost of the product.
        /// </summary>
        public virtual decimal StandardCost
        {
            get
            {
                return this._StandardCost;
            }
            set
            {
                this._StandardCost = value;
            }
        }

    
        /// <summary>
        /// Selling price.
        /// </summary>
        public virtual decimal ListPrice
        {
            get
            {
                return this._ListPrice;
            }
            set
            {
                this._ListPrice = value;
            }
        }

    
        /// <summary>
        /// Product size.
        /// </summary>
        public virtual string Size
        {
            get
            {
                return this._Size;
            }
            set
            {
                this._Size = value;
            }
        }

    
        /// <summary>
        /// Product weight.
        /// </summary>
        public virtual System.Nullable<decimal> Weight
        {
            get
            {
                return this._Weight;
            }
            set
            {
                this._Weight = value;
            }
        }

    
        /// <summary>
        /// Date the product was available for sale.
        /// </summary>
        public virtual System.DateTime SellStartDate
        {
            get
            {
                return this._SellStartDate;
            }
            set
            {
                this._SellStartDate = value;
            }
        }

    
        /// <summary>
        /// Date the product was no longer available for sale.
        /// </summary>
        public virtual System.Nullable<System.DateTime> SellEndDate
        {
            get
            {
                return this._SellEndDate;
            }
            set
            {
                this._SellEndDate = value;
            }
        }

    
        /// <summary>
        /// Date the product was discontinued.
        /// </summary>
        public virtual System.Nullable<System.DateTime> DiscontinuedDate
        {
            get
            {
                return this._DiscontinuedDate;
            }
            set
            {
                this._DiscontinuedDate = value;
            }
        }

    
        /// <summary>
        /// Small image of the product.
        /// </summary>
        public virtual byte[] ThumbNailPhoto
        {
            get
            {
                return this._ThumbNailPhoto;
            }
            set
            {
                this._ThumbNailPhoto = value;
            }
        }

    
        /// <summary>
        /// Small image file name.
        /// </summary>
        public virtual string ThumbnailPhotoFileName
        {
            get
            {
                return this._ThumbnailPhotoFileName;
            }
            set
            {
                this._ThumbnailPhotoFileName = value;
            }
        }

    
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public virtual System.Guid Rowguid
        {
            get
            {
                return this._Rowguid;
            }
            set
            {
                this._Rowguid = value;
            }
        }

    
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        public virtual System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this._ModifiedDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ProductModel in the schema.
        /// </summary>
        public virtual ProductModel ProductModel
        {
            get
            {
                return this._ProductModel;
            }
            set
            {
                this._ProductModel = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ProductCategory in the schema.
        /// </summary>
        public virtual ProductCategory ProductCategory
        {
            get
            {
                return this._ProductCategory;
            }
            set
            {
                this._ProductCategory = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SalesOrderDetails in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet SalesOrderDetails
        {
            get
            {
                return this._SalesOrderDetails;
            }
            set
            {
                this._SalesOrderDetails = value;
            }
        }
    }

}
