//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 18/07/2012 07:55:54
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace Northwind.Domain
{

    /// <summary>
    /// Product descriptions in several languages.
    /// </summary>
    public partial class ProductDescription {

        private int _ProductDescriptionID;

        private string _Description;

        private System.Guid _Rowguid;

        private System.DateTime _ModifiedDate;

        private Iesi.Collections.ISet _ProductModelProductDescriptions;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public ProductDescription()
        {
            this._ProductModelProductDescriptions = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// Primary key for ProductDescription records.
        /// </summary>
        public virtual int ProductDescriptionID
        {
            get
            {
                return this._ProductDescriptionID;
            }
            set
            {
                this._ProductDescriptionID = value;
            }
        }

    
        /// <summary>
        /// Description of the product.
        /// </summary>
        public virtual string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this._Description = value;
            }
        }

    
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public virtual System.Guid Rowguid
        {
            get
            {
                return this._Rowguid;
            }
            set
            {
                this._Rowguid = value;
            }
        }

    
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        public virtual System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this._ModifiedDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ProductModelProductDescriptions in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet ProductModelProductDescriptions
        {
            get
            {
                return this._ProductModelProductDescriptions;
            }
            set
            {
                this._ProductModelProductDescriptions = value;
            }
        }
    }

}
