//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 18/07/2012 07:55:54
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace Northwind.Domain
{

    /// <summary>
    /// There are no comments for ProductModel in the schema.
    /// </summary>
    public partial class ProductModel {

        private int _ProductModelID;

        private string _Name;

        private string _CatalogDescription;

        private System.Guid _Rowguid;

        private System.DateTime _ModifiedDate;

        private Iesi.Collections.ISet _Products;

        private Iesi.Collections.ISet _ProductModelProductDescriptions;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public ProductModel()
        {
            this._Products = new Iesi.Collections.HashedSet();
            this._ProductModelProductDescriptions = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for ProductModelID in the schema.
        /// </summary>
        public virtual int ProductModelID
        {
            get
            {
                return this._ProductModelID;
            }
            set
            {
                this._ProductModelID = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CatalogDescription in the schema.
        /// </summary>
        public virtual string CatalogDescription
        {
            get
            {
                return this._CatalogDescription;
            }
            set
            {
                this._CatalogDescription = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Rowguid in the schema.
        /// </summary>
        public virtual System.Guid Rowguid
        {
            get
            {
                return this._Rowguid;
            }
            set
            {
                this._Rowguid = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ModifiedDate in the schema.
        /// </summary>
        public virtual System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this._ModifiedDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet Products
        {
            get
            {
                return this._Products;
            }
            set
            {
                this._Products = value;
            }
        }

    
        /// <summary>
        /// There are no comments for ProductModelProductDescriptions in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet ProductModelProductDescriptions
        {
            get
            {
                return this._ProductModelProductDescriptions;
            }
            set
            {
                this._ProductModelProductDescriptions = value;
            }
        }
    }

}
