//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 18/07/2012 07:55:54
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace AdventureWorksLT2008Model
{

    /// <summary>
    /// Customer information.
    /// </summary>
    public partial class Customer {

        private int _CustomerID;

        private bool _NameStyle;

        private string _Title;

        private string _FirstName;

        private string _MiddleName;

        private string _LastName;

        private string _Suffix;

        private string _CompanyName;

        private string _SalesPerson;

        private string _EmailAddress;

        private string _Phone;

        private string _PasswordHash;

        private string _PasswordSalt;

        private System.Guid _Rowguid;

        private System.DateTime _ModifiedDate;

        private Iesi.Collections.ISet _CustomerAddresses;

        private Iesi.Collections.ISet _SalesOrderHeaders;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Customer()
        {
            this._CustomerAddresses = new Iesi.Collections.HashedSet();
            this._SalesOrderHeaders = new Iesi.Collections.HashedSet();
            OnCreated();
        }

    
        /// <summary>
        /// Primary key for Customer records.
        /// </summary>
        public virtual int CustomerID
        {
            get
            {
                return this._CustomerID;
            }
            set
            {
                this._CustomerID = value;
            }
        }

    
        /// <summary>
        /// 0 = The data in FirstName and LastName are stored in western style (first name, last name) order.  1 = Eastern style (last name, first name) order.
        /// </summary>
        public virtual bool NameStyle
        {
            get
            {
                return this._NameStyle;
            }
            set
            {
                this._NameStyle = value;
            }
        }

    
        /// <summary>
        /// A courtesy title. For example, Mr. or Ms.
        /// </summary>
        public virtual string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this._Title = value;
            }
        }

    
        /// <summary>
        /// First name of the person.
        /// </summary>
        public virtual string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this._FirstName = value;
            }
        }

    
        /// <summary>
        /// Middle name or middle initial of the person.
        /// </summary>
        public virtual string MiddleName
        {
            get
            {
                return this._MiddleName;
            }
            set
            {
                this._MiddleName = value;
            }
        }

    
        /// <summary>
        /// Last name of the person.
        /// </summary>
        public virtual string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this._LastName = value;
            }
        }

    
        /// <summary>
        /// Surname suffix. For example, Sr. or Jr.
        /// </summary>
        public virtual string Suffix
        {
            get
            {
                return this._Suffix;
            }
            set
            {
                this._Suffix = value;
            }
        }

    
        /// <summary>
        /// The customer's organization.
        /// </summary>
        public virtual string CompanyName
        {
            get
            {
                return this._CompanyName;
            }
            set
            {
                this._CompanyName = value;
            }
        }

    
        /// <summary>
        /// The customer's sales person, an employee of AdventureWorks Cycles.
        /// </summary>
        public virtual string SalesPerson
        {
            get
            {
                return this._SalesPerson;
            }
            set
            {
                this._SalesPerson = value;
            }
        }

    
        /// <summary>
        /// E-mail address for the person.
        /// </summary>
        public virtual string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                this._EmailAddress = value;
            }
        }

    
        /// <summary>
        /// Phone number associated with the person.
        /// </summary>
        public virtual string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this._Phone = value;
            }
        }

    
        /// <summary>
        /// Password for the e-mail account.
        /// </summary>
        public virtual string PasswordHash
        {
            get
            {
                return this._PasswordHash;
            }
            set
            {
                this._PasswordHash = value;
            }
        }

    
        /// <summary>
        /// Random value concatenated with the password string before the password is hashed.
        /// </summary>
        public virtual string PasswordSalt
        {
            get
            {
                return this._PasswordSalt;
            }
            set
            {
                this._PasswordSalt = value;
            }
        }

    
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public virtual System.Guid Rowguid
        {
            get
            {
                return this._Rowguid;
            }
            set
            {
                this._Rowguid = value;
            }
        }

    
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        public virtual System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this._ModifiedDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for CustomerAddresses in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet CustomerAddresses
        {
            get
            {
                return this._CustomerAddresses;
            }
            set
            {
                this._CustomerAddresses = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SalesOrderHeaders in the schema.
        /// </summary>
        public virtual Iesi.Collections.ISet SalesOrderHeaders
        {
            get
            {
                return this._SalesOrderHeaders;
            }
            set
            {
                this._SalesOrderHeaders = value;
            }
        }
    }

}
