//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 18/07/2012 07:55:54
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace AdventureWorksLT2008Model
{

    /// <summary>
    /// Individual products associated with a specific sales order. See SalesOrderHeader.
    /// </summary>
    public partial class SalesOrderDetail {

        private int _SalesOrderID;

        private int _SalesOrderDetailID;

        private short _OrderQty;

        private decimal _UnitPrice;

        private decimal _UnitPriceDiscount;

        private decimal _LineTotal;

        private System.Guid _Rowguid;

        private System.DateTime _ModifiedDate;

        private SalesOrderHeader _SalesOrderHeader;

        private Product _Product;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          SalesOrderDetail toCompare = obj as SalesOrderDetail;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.SalesOrderID, toCompare.SalesOrderID))
            return false;
          if (!Object.Equals(this.SalesOrderDetailID, toCompare.SalesOrderDetailID))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + SalesOrderID.GetHashCode();
          hashCode = (hashCode * 7) + SalesOrderDetailID.GetHashCode();
          return hashCode;
        }
        
        #endregion

        public SalesOrderDetail()
        {
            OnCreated();
        }

    
        /// <summary>
        /// Primary key. Foreign key to SalesOrderHeader.SalesOrderID.
        /// </summary>
        public virtual int SalesOrderID
        {
            get
            {
                return this._SalesOrderID;
            }
            set
            {
                this._SalesOrderID = value;
            }
        }

    
        /// <summary>
        /// Primary key. One incremental unique number per product sold.
        /// </summary>
        public virtual int SalesOrderDetailID
        {
            get
            {
                return this._SalesOrderDetailID;
            }
            set
            {
                this._SalesOrderDetailID = value;
            }
        }

    
        /// <summary>
        /// Quantity ordered per product.
        /// </summary>
        public virtual short OrderQty
        {
            get
            {
                return this._OrderQty;
            }
            set
            {
                this._OrderQty = value;
            }
        }

    
        /// <summary>
        /// Selling price of a single product.
        /// </summary>
        public virtual decimal UnitPrice
        {
            get
            {
                return this._UnitPrice;
            }
            set
            {
                this._UnitPrice = value;
            }
        }

    
        /// <summary>
        /// Discount amount.
        /// </summary>
        public virtual decimal UnitPriceDiscount
        {
            get
            {
                return this._UnitPriceDiscount;
            }
            set
            {
                this._UnitPriceDiscount = value;
            }
        }

    
        /// <summary>
        /// Per product subtotal. Computed as UnitPrice * (1 - UnitPriceDiscount) * OrderQty.
        /// </summary>
        public virtual decimal LineTotal
        {
            get
            {
                return this._LineTotal;
            }
            set
            {
                this._LineTotal = value;
            }
        }

    
        /// <summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        /// </summary>
        public virtual System.Guid Rowguid
        {
            get
            {
                return this._Rowguid;
            }
            set
            {
                this._Rowguid = value;
            }
        }

    
        /// <summary>
        /// Date and time the record was last updated.
        /// </summary>
        public virtual System.DateTime ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this._ModifiedDate = value;
            }
        }

    
        /// <summary>
        /// There are no comments for SalesOrderHeader in the schema.
        /// </summary>
        public virtual SalesOrderHeader SalesOrderHeader
        {
            get
            {
                return this._SalesOrderHeader;
            }
            set
            {
                this._SalesOrderHeader = value;
            }
        }

    
        /// <summary>
        /// There are no comments for Product in the schema.
        /// </summary>
        public virtual Product Product
        {
            get
            {
                return this._Product;
            }
            set
            {
                this._Product = value;
            }
        }
    }

}
