//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate Fluent Mapping template.
// Code is generated on: 18/07/2012 07:55:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using FluentNHibernate.Mapping;
using FluentNHibernate.MappingModel.Collections;

namespace AdventureWorksLT2008Model
{
    public class ProductModelProductDescriptionMap : ClassMap<ProductModelProductDescription>
    {
        public ProductModelProductDescriptionMap()
        {
              Schema("SalesLT");
              Table("ProductModelProductDescription");
              LazyLoad();
              CompositeId()
                .KeyProperty(x => x.ProductModelID, set => {
                    set.Type("Int32");
                    set.ColumnName("ProductModelID");
                    set.Access.Property(); } )
                .KeyProperty(x => x.ProductDescriptionID, set => {
                    set.Type("Int32");
                    set.ColumnName("ProductDescriptionID");
                    set.Access.Property(); } )
                .KeyProperty(x => x.Culture, set => {
                    set.Type("String");
                    set.ColumnName("Culture");
                    set.Length(6);
                    set.Access.Property(); } );
              Map(x => x.Rowguid)    
                .Column("rowguid")
                .CustomType("Guid")
                .Access.Property()
                .Generated.Never()
                .Default("newid()")
                .CustomSqlType("uniqueidentifier")
                .Not.Nullable()
                .Unique();
              Map(x => x.ModifiedDate)    
                .Column("ModifiedDate")
                .CustomType("DateTime")
                .Access.Property()
                .Generated.Never()
                .Default("getdate()")
                .CustomSqlType("datetime")
                .Not.Nullable();
              References(x => x.ProductDescription)
                .Class<ProductDescription>()
                .Access.Property()
                .Cascade.None()
                .LazyLoad()
                .Columns("ProductDescriptionID");
              References(x => x.ProductModel)
                .Class<ProductModel>()
                .Access.Property()
                .Cascade.None()
                .LazyLoad()
                .Columns("ProductModelID");
        }
    }

}
